<testWidget>:
	canvas.before:
		Rectangle:
			pos: self.pos
			size: self.size
			source: 'Map1.jpg'
	Image:
		source: 'red45right.png'
		size: 50, 50
		id: image1
		pos: 440,100
		opacity: 0
	Image:
		source: 'red45right.png'
		size: 50, 50
		id: image2
		pos: 550,210
		opacity: 0
	Image:
		source: 'red45left.png'
		size: 50, 50
		id: image3
		pos: 670,380
		opacity: 0
	Image:
		source: 'redtop.png'
		size: 50, 50
		id: image4
		pos: 425,535
		opacity: 0
		
	
			
		
	
