<testWidget>:
	canvas.before:
		Rectangle:
			pos: self.pos
			size: self.size
			source: 'Map1s.jpg'
	Image:
		source: 'redright.png'
		size: 50, 50
		id: image1
		pos: 440,400
		opacity: 0
	Image:
		source: 'red45right.png'
		size: 50, 50
		id: image2
		pos: 690,340
		opacity: 0
	Image:
		source: 'redright.png'
		size: 50, 50
		id: image3
		pos: 900,500
		opacity: 0
	Image:
		source: 'redtop.png'
		size: 50, 50
		id: image4
		pos: 555,570
		opacity: 0
		
	
			
		
	
